import "./globals.css";
import Header from "../../components/header/index";
import Footer from "../../components/footer/index";
import ReduxProvider from "../../provider/ReduxProvider";
import { Directions, Languages } from "../../constance/enums";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { LocaleType } from "../../i18n.config";
export const generateStaticParams = async () => [
  { locale: Languages.ENGLISH },
  { locale: Languages.ARABIC },
];

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: LocaleType }>;
}>) {
  const locale = (await params).locale;
  return (
    <html
      lang={locale}
      dir={locale === Languages.ARABIC ? Directions.RTL : Directions.LTR}
    >
      <body className={roboto.className}>
        {" "}
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
